config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :file_uploads, only: %i[index new create show]
  resources :general, only: [:index] do
    collection do
      post :import
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compliance.rb
class Compliance < ApplicationRecord
end

app/models/construction.rb
class Construction < ApplicationRecord
end

app/models/dhw_generator.rb
class DhwGenerator < ApplicationRecord
end

app/models/door.rb
class Door < ApplicationRecord
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  # has one_attached :file
  has_one_attached :file
  has_one :general, dependent: :destroy
  validates :file_name, presence: true
  validates :email, presence: true

  def self.general
    General.find(general_id)
  end
end

app/models/general.rb
class General < ApplicationRecord
  belongs_to :file_upload

  def self.file_upload
    FileUpload.find(file_upload_id)
  end
end

app/models/glass.rb
class Glass < ApplicationRecord
end

app/models/hvac_system.rb
class HvacSystem < ApplicationRecord
end

app/models/rec_user.rb
class RecUser < ApplicationRecord
end

app/models/wall.rb
class Wall < ApplicationRecord
end

app/models/window.rb
class Window < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning, :success
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def new
    @file_upload = FileUpload.new
  end

  def create
    file_name = params[:file_upload][:file]&.original_filename
    email = params[:file_upload][:email]
    file = params[:file_upload][:file]

    render :new unless file.present? && email.present? && file.content_type == 'application/octet-stream'

    @file_upload = FileUpload.new(file_name: file_name, email: email, file: file)

    if @file_upload.save
      ImportFileUploadJob.perform_now(@file_upload)
      redirect_to file_uploads_path
    else
      render :new
    end
  end

  def index
    @file_uploads = FileUpload.all
  end

  def show
    @file_upload = FileUpload.find(params[:id])
    @array_objects = []
    @general = [@file_upload.general]
    @rec_user = RecUser.where(file_upload_id: @file_upload.id).to_a
    @glass = Glass.where(file_upload_id: @file_upload.id).to_a
    @zone = Zone.where(file_upload_id: @file_upload.id).to_a
    @door = Door.where(file_upload_id: @file_upload.id).to_a
    @dhw_generator = DhwGenerator.where(file_upload_id: @file_upload.id).to_a
    @wall = Wall.where(file_upload_id: @file_upload.id).to_a
    @construction = Construction.where(file_upload_id: @file_upload.id).to_a
    @hvac_system = HvacSystem.where(file_upload_id: @file_upload.id).to_a
    @compliance = Compliance.where(file_upload_id: @file_upload.id).to_a
    @window = Window.where(file_upload_id: @file_upload.id).to_a
    @array_objects << @general << @rec_user << @glass << @zone << @door << @dhw_generator << @wall << @construction << @hvac_system << @compliance << @window
  end

  private

  def file_upload_params
    params.require(:file_upload).permit(:file_name, :email, :file)
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

end

app/controllers/helper_controller.rb
class HelperController < ApplicationController
  def self.import(file_upload)
    return false if file_upload.blank? || file_upload&.file.blank?

    objects_created = []

    model_params = parser(file_upload.file)

    model_params.each do |model_name, params|
      model_name = model_name.gsub(/\d+/, '').split(/ |-/).map(&:capitalize).join('')
      # check if model_name is a valid model
      next unless Object.const_defined?(model_name)

      model = model_name.constantize
      values = serialize(params, model)
      next if values.blank?

      model_object = model.new(values)

      model_object.file_upload_id = file_upload.file.id
      model_object.save
      objects_created << model_object
    end
    objects_created
  end

  def self.parser(file)
    hash_model = {}
    count = 0
    formatted_name = ''
    file.open do |file_input|
      File.read(file_input).split("\n").each do |row|
        row.lstrip!
        regex = /(\S*).*=(.*)/.match(row)
        next if row.match(/\.\./) || row.match(/ˆ\$/) || regex.blank?

        key = regex[1].gsub('-', '_').downcase
        value = regex[2].lstrip
        formatted_name = if key.match(/".*?"/)
                           count += 1
                           "#{value.capitalize}#{count}"
                         else
                           formatted_name
                         end
        if hash_model[formatted_name].nil?
          hash_model[formatted_name] = {}
        else
          hash_model[formatted_name][key.to_sym] = value
        end
      end
    end
    hash_model
  end

  def self.serialize(hash_model, model)
    hash_model.each do |key, value|
      key == 'type' && key = model.class.name.downcase._.key
      unless model.column_names.include?(key.to_s)
        hash_model.delete(key)
        next
      end

      case model.column_for_attribute(key.to_s).type
      when :float
        hash_model[key] = value.to_f
      when :boolean
        hash_model[key] = value.upcase == 'YES'
      when :integer
        hash_model[key] = value.to_i
      when :date
        value = value.gsub(/{|}| /, '').gsub(',', '-')
        hash_model[key] = Date.parse(value, '%Y-%m-%d')
      else
        hash_model[key] = value
      end
    end
    hash_model
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/file_uploads/index.html.erb
<div class="container mt-3">
  <h2><strong>Files</strong></h2>
  <div class="cards">
    <% @file_uploads.each do |file_upload| %>
      <div class="card-file_upload">
        <div class="card-file_upload-right d-flex align-items-start flex-column">
          <div class="card-file_upload-right-email">
          <table>
            <tr>
              <td>
                <p>
                  File imported <%= file_upload.file_name.truncate(50) %> by <%= file_upload.email %>
                </p>
              </td>
              <td>
                <% if file_upload.general.present? %>
                  <%= link_to "Show", file_upload_path(file_upload), class: "btn btn-primary" %>
                <% end %>
              </td>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/file_uploads/new.html.erb
<div class="container my-5">
  <h1>Import a file:</h1>
 <%= simple_form_for [@file_upload ] do |f| %>
  <%= f.input :email, required: :true %>
  <%= f.input :file, as: :file, required: :true%>
  <div class="row mt-3 ml-1">
    <%= f.submit "Confirm", class: "btn btn-primary"%>
    <%= link_to 'Go Back', root_path, class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/file_uploads/show.html.erb
<div class="container mt-3">
  <div class="cards">
  <h2>FileName: <%= @file_upload.file_name %> </h2>
    <% @array_objects.each do |object| %>
        <h2><%= object.first.class.name %> </h2>
        <% object.each do |model| %>
          <% model.attributes.each do |key, value| %>
            <p><%= key %> = <%= value %></p>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>