config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :file_uploads, only: %i[index new create show]
  resources :general, only: [:index] do
    collection do
      post :import
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compliance.rb
class Compliance < ApplicationRecord
end

app/models/construction.rb
class Construction < ApplicationRecord
end

app/models/dhw_generator.rb
class DhwGenerator < ApplicationRecord
end

app/models/door.rb
class Door < ApplicationRecord
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  # has one_attached :file
  has_one_attached :file
  has_one :general, dependent: :destroy
  validates :file_name, presence: true
  validates :email, presence: true

  def self.general
    General.find(general_id)
  end
end

app/models/general.rb
class General < ApplicationRecord
  belongs_to :file_upload

  def self.file_upload
    FileUpload.find(file_upload_id)
  end
end

app/models/glass.rb
class Glass < ApplicationRecord
end

app/models/hvac_system.rb
class HvacSystem < ApplicationRecord
end

app/models/rec_user.rb
class RecUser < ApplicationRecord
end

app/models/wall.rb
class Wall < ApplicationRecord
end

app/models/window.rb
class Window < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

end

app/controllers/helper_controller.rb
class HelperController < ApplicationController
  def self.import(file_upload)
    return false if file_upload.blank? || file_upload&.file.blank?

    objects_created = []

    model_params = parser(file_upload.file)

    model_params.each do |model_name, params|
      model_name = model_name.gsub(/\d+/, '').split(/ |-/).map(&:capitalize).join('')
      # check if model_name is a valid model
      next unless Object.const_defined?(model_name)

      model = model_name.constantize
      values = serialize(params, model)
      next if values.blank?

      model_object = model.new(values)

      model_object.file_upload_id = file_upload.file.id
      model_object.save
      objects_created << model_object
    end
    objects_created
  end

  def self.parser(file)
    hash_model = {}
    count = 0
    formatted_name = ''
    file.open do |file_input|
      File.read(file_input).split("\n").each do |row|
        row.lstrip!
        regex = /(\S*).*=(.*)/.match(row)
        next if row.match(/\.\./) || row.match(/ˆ\$/) || regex.blank?

        key = regex[1].gsub('-', '_').downcase
        value = regex[2].lstrip
        formatted_name = if key.match(/".*?"/)
                           count += 1
                           "#{value.capitalize}#{count}"
                         else
                           formatted_name
                         end
        if hash_model[formatted_name].nil?
          hash_model[formatted_name] = {}
        else
          hash_model[formatted_name][key.to_sym] = value
        end
      end
    end
    hash_model
  end

  def self.serialize(hash_model, model)
    hash_model.each do |key, value|
      key == 'type' && key = model.class.name.downcase._.key
      unless model.column_names.include?(key.to_s)
        hash_model.delete(key)
        next
      end

      case model.column_for_attribute(key.to_s).type
      when :float
        hash_model[key] = value.to_f
      when :boolean
        hash_model[key] = value.upcase == 'YES'
      when :integer
        hash_model[key] = value.to_i
      when :date
        value = value.gsub(/{|}| /, '').gsub(',', '-')
        hash_model[key] = Date.parse(value, '%Y-%m-%d')
      else
        hash_model[key] = value
      end
    end
    hash_model
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArbncoTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_flash.html.erb
<div id="flash_messages">
<% if !flash.empty? %>
  <% flash.each do |key, value| %>
    <% if value && !value.empty? && ['success', 'error', 'notice', 'warning'].include?(key) %>
      <div class="flash <%= key %>">
        <div>
          <div class="flash-inner">
            <%= value %>
          </div>
          <span><%= image_tag 'x-black.svg' %></span>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("banner.png") %>);">
  <div class="container">
    <h1>Upload your input files easily!</h1>
  </div>
</div>


<%# add a simple form for input a file%>
<div class="container">
  <div class="row">
  <%# redirect to file_uploads new path%>
  <%= link_to "Upload your input files", new_file_upload_path, class: "btn btn-primary" %>
  </div>
</div>